#!/bin/bash

src=$( wget xkcd.com -q -O - )
embed=$( echo "$src" | perl -n -e'/Image URL .*?(https.*?)\n/ && print $1' )
title=$( echo "$src" | perl -n -e'/<div id="ctitle">(.*?)<\/div>/ && print $1' )
subtext=$( echo "$src" | perl -n -e'/<img src=".*?" title="(.*?)"/ && print $1' )
id=$( echo "$src" | perl -n -e'/"og:url" content=.*?\/([0-9]+)\// && print $1' )

echo "# <b>$title</b>

[![]($embed)](https://xkcd.com/$id)

<i>$subtext</i>

<div style=\"text-align: right\">
  Fetched directly from
  <a href=\"https://xkcd.com\">
    xkcd
  </a>
  <br>
  Permalink to this comic:
  <a href=\"https://xkcd.com/$id\">
    https://xkcd.com/$id
  </a>
  <br>
  Need an explanation ?
  <a href=\"https://www.explainxkcd.com/wiki/index.php/$id\">
    Explain xkcd
  </a>
  <br>
</div>" > README.md
