#!/bin/bash

src=$( wget xkcd.com -q -O - )
embed=$( echo "$src" | perl -n -e'/Image URL .*?(https.*?)"/ && print $1' )
title=$( echo "$src" | perl -n -e'/<div id="ctitle">(.*?)<\/div>/ && print $1' )
subtext=$( echo "$src" | perl -n -e'/<img src=".*?" title="(.*?)"/ && print $1' )
id=$( echo "$src" | perl -n -e'/"og:url" content=.*?\/([0-9]+)\// && print $1' )

echo "# <b>$title</b>

[![]($embed)](https://xkcd.com/$id)

<i>$subtext</i>

<div align=\"right\">
  Fetched directly from
  <a href=\"https://xkcd.com\">
    xkcd
  </a>
  by
  <a href=\"https://github.com/Vanille-N/Vanille-N/blob/master/fetch\">
    this bash script
  </a>
</div>
<div align=\"right\">
  Permalink to this comic:
  <a href=\"https://xkcd.com/$id\">
    https://xkcd.com/$id
  </a>
</div>
<div align=\"right\">
  Need an explanation ?
  <a href=\"https://www.explainxkcd.com/wiki/index.php/$id\">
    Explain xkcd
  </a>
</div>
<div align=\"right\">
  How does this work ?
  <a href=\"https://github.com/Vanille-N/Vanille-N/blob/master/.github/workflows/build.yml\">
    workflow
  </a>
  |
  <a href=\"https://simonwillison.net/2020/Jul/10/self-updating-profile-readme/\">
    related explanation
  </a>
</div><br>

<a href=\"https://github.com/Vanille-N/Vanille-N/actions\"><img src=\"https://github.com/Vanille-N/Vanille-N/workflows/Build%20README/badge.svg\" align=\"right\" alt=\"Build README\"></a>" > README.md
